// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SuiQuickRecorderWebAPI.Data;

#nullable disable

namespace SuiQuickRecorderWebAPI.Migrations
{
    [DbContext(typeof(SuiContext))]
    partial class SuiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SuiQuickRecorderWebAPI.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Alts")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("alts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("SuiQuickRecorderWebAPI.Entities.CategoryIn", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Alts")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("alts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("categories_in", (string)null);
                });

            modelBuilder.Entity("SuiQuickRecorderWebAPI.Entities.CategoryOut", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Alts")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("alts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("categories_out", (string)null);
                });

            modelBuilder.Entity("SuiQuickRecorderWebAPI.Entities.Loaner", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Alts")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("alts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("loaners", (string)null);
                });

            modelBuilder.Entity("SuiQuickRecorderWebAPI.Entities.Store", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Alts")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("alts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("stores", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
